---

# This file is a YAML formatted file. YAML indenting is done in spaces not
# tabs, and whitespace is significant. If you don't stick to this, it will
# fail on provision

# These are your website, and their names plugins/themes they're
# located in. See the docs for how to define these, and what all the keys
# and options are
# Remember, whitespace is significant! Tabs and spaces mean different things
app:

  setup:
    workflow: cdk-comp/bedrock
    wordpress: 4.9.9
    env: false
    shell: false
    plugins: true
    theme: true
    settings: true
    extra: false
    
  env:
    app_host: weski.in

  plugins:
    single:
      - name: advanced-custom-fields
        package: wp-cli
        ver: *
        zip: ""
      - name: duplicate-post
        package: wp-cli
        ver: *
        zip: ""
      - name: elementor
        package: wp-cli
        ver: *
        zip: ""
      - name: wordfence
        package: wp-cli
        ver: *
        zip: ""
      - name: wordpress-seo
        package: wp-cli
        ver: *
        zip: ""
      - name: wp-mail-smtp
        package: wp-cli
        ver: *
        zip: ""
      - name: pojo-accessibility
        package: wp-cli
        ver: *
        zip: ""
      - name: advanced-custom-fields-pro
        package: wp-pro-club
        ver: v5.7.10
        zip: ""
      - name: elementor-pro
        package: wp-pro-club
        ver: v2.4.2
        zip: ""
      - name: jet-elements
        package: wp-pro-club
        ver: v1.14.10
        zip: ""
      - name: jet-menu
        package: wp-pro-club
        ver: v1.5.5
        zip: ""
      - name: wp-rocket
        package: wp-pro-club
        ver: v3.2.3.1
        zip: ""

  theme:
    name: elementor-hello-theme
    package: wp-cli
    ver: *
    zip: https://github.com/cdk-comp/elementor-hello-theme/archive/master.zip
    
  settings:
    # Discussion
    comment_moderation: 1
    comment_registration: 1
    default_comment_status: 0
    default_pingback_flag: 0
    default_ping_status: 0
    # General
    blogdescription: brandizone
    date_format: d/m/Y
    time_format: H:i
    timezone_string: Asia/Jerusalem
    start_of_week: 0
    # Media
    large_size_h: 0
    large_size_w: 0
    medium_size_h: 0
    medium_size_w: 0
    thumbnail_crop: 0
    thumbnail_size_h: 375
    thumbnail_size_w: 375
    # Miscellaneous
    convert_smilies: false
    uploads_use_yearmonth_folders: 0
    # Permalinks
    permalink_structure: /%postname%/
    # Privacy
    blog_public: 0
    # Reading
    frontpage_name: Homepage
    page_on_front: 4
    show_on_front: page
    # User
    admin_email: cdk@cdk.co.il
    admin_password: password
    admin_user: cdk-admin
    first_name: Dima
    last_name: Minka

  config_templates:
    workflow: default
    env: default
    plugins_single: default
    theme: default
    settings: default
    extra: default
